### PR TITLE
ML-950 allow custom objects passed to Rollbar in Boomified errors

### PR DESCRIPTION
**Pull request by paulojblack**
Description of changes found in README

### CODE REVIEW

**Review by clok — CHANGES_REQUESTED** [review]
Please update the PR title with a descriptive title that includes the ticket number at the beginning.

**Review by clok — CHANGES_REQUESTED** [review]
Please add tests for the modifications made.

**Review by clok — APPROVED** [review]
:shipit:

**Comment by paulojblack** [comment]
im going to wait to merge this until the pr for api looking glass is ready so it can be more easily tested in staging

**Pull request merged**
